version: '3.8'

services:
  web:
    build: .
    command: ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8000", "--log_config", "log_config.ini"]
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A celery_task.celery_app worker --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A celery_task.celery_app beat --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis

  redis:
    image: redis:3.2
    ports:
      - "26379:6379"
